import { notFound } from "next/navigation";
import { getReportWithEntries } from "@/app/actions/reports";
import { auth } from "@/lib/auth";
import { REWARD_TIERS } from "@/lib/rewards";
import { getSASTNow } from "@/lib/sast";
import ExportButton from "./export-button";
import ApproveButton from "../approve-button";
import ReportTable from "./report-table";

export default async function ReportDetailPage({
  params,
}: {
  params: Promise<{ month: string }>;
}) {
  const { month: reportId } = await params;
  const [report, session] = await Promise.all([
    getReportWithEntries(reportId),
    auth(),
  ]);

  if (!report) notFound();

  const role = session?.user?.role;

  const { year, month } = getSASTNow();
  const currentYM = `${year}-${String(month).padStart(2, "0")}`;
  const monthComplete = report.month < currentYM;

  const totalSats = report.entries.reduce((sum, e) => sum + e.rewardSats, 0);
  const totalParticipants = report.entries.length;
  const avgPercentage =
    totalParticipants > 0
      ? report.entries.reduce((sum, e) => sum + Number(e.percentage), 0) / totalParticipants
      : 0;
  const qualifyingParticipants = report.entries.filter((e) => e.rewardSats > 0).length;

  const tierCounts = REWARD_TIERS.map((tier) => ({
    ...tier,
    count: report.entries.filter((e) => {
      const pct = Number(e.percentage);
      if (tier.sats === 7500) return pct >= 100;
      return pct >= tier.min && pct <= tier.max;
    }).length,
  }));

  return (
    <div>
      <div className="flex items-start justify-between">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">Report: {report.month}</h2>
          <p className="mt-1 text-sm text-gray-500">
            Generated by {report.generator.name} on {report.generatedAt.toLocaleDateString()}
          </p>
          {report.status === "APPROVED" && report.approver && (
            <p className="mt-1 text-sm text-green-600">
              Approved by {report.approver.name} on{" "}
              {report.approvedAt?.toLocaleDateString()}
            </p>
          )}
        </div>
        <div className="flex items-center gap-3">
          {report.status === "APPROVED" ? (
            <span className="inline-flex rounded-full bg-green-100 px-3 py-1 text-sm font-medium text-green-700">
              Approved
            </span>
          ) : (
            <span className="inline-flex rounded-full bg-yellow-100 px-3 py-1 text-sm font-medium text-yellow-700">
              Pending Approval
            </span>
          )}
          <ExportButton reportId={report.id} month={report.month} />
          {role === "ADMINISTRATOR" && report.status === "PENDING" && (
            <ApproveButton reportId={report.id} disabled={!monthComplete} />
          )}
        </div>
      </div>

      {/* Summary cards */}
      <div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-4">
        <div className="rounded-lg border border-gray-200 bg-white p-4">
          <p className="text-sm text-gray-500">Total Participants</p>
          <p className="mt-1 text-2xl font-bold">{totalParticipants}</p>
        </div>
        <div className="rounded-lg border border-gray-200 bg-white p-4">
          <p className="text-sm text-gray-500">Qualifying</p>
          <p className="mt-1 text-2xl font-bold text-green-600">{qualifyingParticipants}</p>
        </div>
        <div className="rounded-lg border border-gray-200 bg-white p-4">
          <p className="text-sm text-gray-500">Average Attendance</p>
          <p className="mt-1 text-2xl font-bold">{avgPercentage.toFixed(1)}%</p>
        </div>
        <div className="rounded-lg border border-gray-200 bg-white p-4">
          <p className="text-sm text-gray-500">Total Rewards</p>
          <p className="mt-1 text-2xl font-bold text-orange-600">
            🗲 {totalSats.toLocaleString()} sats
          </p>
        </div>
      </div>

      {/* Tier breakdown */}
      <div className="mt-6 rounded-lg border border-gray-200 bg-white p-6">
        <h3 className="text-lg font-semibold text-gray-900">Reward Tier Breakdown</h3>
        <div className="mt-4 grid grid-cols-5 gap-4">
          {tierCounts.map((tier) => (
            <div key={tier.label} className="text-center">
              <p className={`text-lg font-bold ${tier.color}`}>{tier.count}</p>
              <p className="text-xs text-gray-500">{tier.label}</p>
              <p className="text-xs font-medium text-gray-700">
                {tier.sats > 0 ? `🗲 ${tier.sats} sats` : "No reward"}
              </p>
            </div>
          ))}
        </div>
      </div>

      <ReportTable entries={report.entries.map(e => ({
        ...e,
        percentage: e.percentage.toString(),
        participant: {
          tskId: e.participant.tskId,
          surname: e.participant.surname,
          fullNames: e.participant.fullNames,
          knownAs: e.participant.knownAs,
          dateOfBirth: e.participant.dateOfBirth,
          gender: e.participant.gender,
          isJuniorCoach: e.participant.isJuniorCoach,
        },
      }))} />
    </div>
  );
}
