import { prisma } from "@/lib/db";
import { auth } from "@/lib/auth";
import Link from "next/link";
import { getSASTNow, getStartOfSASTMonth, getEndOfSASTMonth } from "@/lib/sast";
import { fmtDate } from "@/lib/format-date";

const categoryLabels: Record<string, string> = {
  SURFING: "Surfing",
  FITNESS: "Fitness",
  SKATING: "Skating",
  BEACH_CLEAN_UP: "Beach Clean Up",
  OTHER: "Other",
};

export default async function DashboardPage() {
  const session = await auth();
  const role = session?.user?.role;

  const { year, month } = getSASTNow();
  const currentMonth = `${year}-${String(month).padStart(2, "0")}`;
  const monthStart = getStartOfSASTMonth(currentMonth);
  const monthEnd = getEndOfSASTMonth(currentMonth);

  const [activeCount, thisMonthEvents, recentEvents, recentReports] =
    await Promise.all([
      prisma.participant.count({ where: { status: "ACTIVE" } }),
      prisma.event.count({ where: { date: { gte: monthStart, lte: monthEnd } } }),
      prisma.event.findMany({
        orderBy: { date: "desc" },
        take: 5,
        include: {
          _count: { select: { attendanceRecords: true } },
        },
      }),
      prisma.monthlyReport.findMany({
        orderBy: { generatedAt: "desc" },
        take: 5,
      }),
    ]);

  return (
    <div>
      <h2 className="text-2xl font-bold text-gray-900">Dashboard</h2>

<div className="mt-6 grid grid-cols-1 gap-6 sm:grid-cols-3">
        <div className="rounded-lg border border-gray-200 bg-white p-6">
          <p className="text-sm font-medium text-gray-500">Active Participants</p>
          <p className="mt-2 text-3xl font-bold text-gray-900">{activeCount}</p>
        </div>
        <div className="rounded-lg border border-gray-200 bg-white p-6">
          <p className="text-sm font-medium text-gray-500">Events This Month</p>
          <p className="mt-2 text-3xl font-bold text-gray-900">{thisMonthEvents}</p>
        </div>
        <div className="rounded-lg border border-gray-200 bg-white p-6">
          <p className="text-sm font-medium text-gray-500">Reports Generated</p>
          <p className="mt-2 text-3xl font-bold text-gray-900">{recentReports.length}</p>
        </div>
      </div>

      <div className="mt-8 grid grid-cols-1 gap-6 lg:grid-cols-2">
        <div className="rounded-lg border border-gray-200 bg-white p-6">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-semibold text-gray-900">Recent Events</h3>
            <Link href="/attendance" className="text-sm text-orange-600 hover:text-orange-800">
              View all
            </Link>
          </div>
          {recentEvents.length === 0 ? (
            <p className="mt-4 text-sm text-gray-500">
              No events yet. Create one from the Attendance page.
            </p>
          ) : (
            <table className="mt-4 w-full text-sm">
              <thead>
                <tr className="border-b text-left text-gray-500">
                  <th className="pb-2">Date</th>
                  <th className="pb-2">Category</th>
                  <th className="pb-2">Marked</th>
                </tr>
              </thead>
              <tbody>
                {recentEvents.map((event) => (
                  <tr key={event.id} className="border-b last:border-0">
                    <td className="py-2">{fmtDate(event.date)}</td>
                    <td className="py-2 text-gray-600">
                      {categoryLabels[event.category] || event.category}
                    </td>
                    <td className="py-2">{event._count.attendanceRecords}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>

        {role === "ADMINISTRATOR" && (
          <div className="rounded-lg border border-gray-200 bg-white p-6">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-semibold text-gray-900">Recent Reports</h3>
              <Link href="/reports" className="text-sm text-orange-600 hover:text-orange-800">
                View all
              </Link>
            </div>
            {recentReports.length === 0 ? (
              <p className="mt-4 text-sm text-gray-500">
                No reports yet.
              </p>
            ) : (
              <table className="mt-4 w-full text-sm">
                <thead>
                  <tr className="border-b text-left text-gray-500">
                    <th className="pb-2">Month</th>
                    <th className="pb-2">Status</th>
                    <th className="pb-2">Generated by</th>
                  </tr>
                </thead>
                <tbody>
                  {recentReports.map((report) => (
                    <tr key={report.id} className="border-b last:border-0">
                      <td className="py-2 font-medium">
                        <Link href={`/reports/${report.id}`} className="text-orange-600 hover:text-orange-800">
                          {report.month}
                        </Link>
                      </td>
                      <td className="py-2">
                        <span
                          className={`inline-flex rounded-full px-2 py-0.5 text-xs font-medium ${
                            report.status === "APPROVED"
                              ? "bg-green-100 text-green-700"
                              : "bg-yellow-100 text-yellow-700"
                          }`}
                        >
                          {report.status === "APPROVED" ? "Approved" : "Pending"}
                        </span>
                      </td>
                      <td className="py-2 text-gray-600">{report.generatedBy}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
